In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Function to get files in the location

import os
for dirname, _, filenames in os.walk('C:/Users/Sameer Thakare/titanic/titanic'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


C:/Users/Sameer Thakare/titanic/titanic\gender_submission.csv
C:/Users/Sameer Thakare/titanic/titanic\test.csv
C:/Users/Sameer Thakare/titanic/titanic\train.csv


In [2]:
# Load the titanic data

train_data = pd.read_csv("C:/Users/Sameer Thakare/titanic/titanic/train.csv")
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
len(train_data)

891

In [5]:
train_data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [6]:
# Load test data

test_data = pd.read_csv("C:/Users/Sameer Thakare/titanic/titanic/test.csv")
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [7]:
women = train_data.loc[train_data.Sex == 'female']["Survived"]
rate_women = sum(women)/len(women)

print("% of women who survived:", rate_women)

% of women who survived: 0.7420382165605095


In [8]:
men = train_data.loc[train_data.Sex == 'male']["Survived"]
rate_men = sum(men)/len(men)

print("% of men who survived:", rate_men)

% of men who survived: 0.18890814558058924


In [12]:
# A simple way to split data is using sklearn

from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(train_data, test_size=0.2, random_state=42)

In [13]:
'''
# stratified splitting

from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in split.split(train_data):
    strat_train_set = train_data.loc[train_index]
    strat_test_set = train_data.loc[test_index]
'''

'\n# stratified splitting\n\nfrom sklearn.model_selection import StratifiedShuffleSplit\n\nsplit = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)\n\nfor train_index, test_index in split.split(train_data):\n    strat_train_set = train_data.loc[train_index]\n    strat_test_set = train_data.loc[test_index]\n'

In [14]:
# put the test set aside and you are only exploring the training set

titanic = train_set.copy()

In [15]:
# Looking for Correlations

# features = ["Pclass", "Sex", "SibSp", "Parch", "Survived", "Age", "Fare", "Embarked"]
# X = pd.get_dummies(titanic[features])
# len(titanic)

In [16]:
# corr_matrix = X.corr()
# corr_matrix["Survived"].sort_values(ascending=False)

In [17]:
# X["total_family"] = X["SibSp"] + X["Parch"]
# X["value"] = X["Fare"]/X["Pclass"]
# corr_matrix = X.corr()
# corr_matrix["Survived"].sort_values(ascending = False)

In [18]:
train_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [19]:
# taking only important features

num_features = [ "Age", "SibSp", "Parch", "Fare", "Pclass"]
cat_features = [ "Sex"]
lable_feature = ["Survived"]

total_features = num_features + cat_features

imp_features = num_features + cat_features

titanic_new = train_set[imp_features] 

In [20]:
list(titanic_new)

['Age', 'SibSp', 'Parch', 'Fare', 'Pclass', 'Sex']

In [21]:
train_data[imp_features]

Age  SibSp  Parch     Fare  Pclass     Sex
0    22.0      1      0   7.2500       3    male
1    38.0      1      0  71.2833       1  female
2    26.0      0      0   7.9250       3  female
3    35.0      1      0  53.1000       1  female
4    35.0      0      0   8.0500       3    male
..    ...    ...    ...      ...     ...     ...
886  27.0      0      0  13.0000       2    male
887  19.0      0      0  30.0000       1  female
888   NaN      1      2  23.4500       3  female
889  26.0      0      0  30.0000       1    male
890  32.0      0      0   7.7500       3    male

[891 rows x 6 columns]

In [22]:
from sklearn.base import BaseEstimator, TransformerMixin

SisSp_ix, Parch_ix, Fare_ix, Pclass_ix  = 1, 2, 3, 4

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, total_family = True): # no *args or **kargs
        self.total_family = total_family
 
    def fit(self, X, y=None):
        return self # nothing else to do

    def transform(self, X, y=None):
        value = X[:, SisSp_ix] / X[:, Pclass_ix]
        # population_per_household = X[:, population_ix] / X[:, household_ix]
    
        if self.total_family:
            total_family = X[:, SisSp_ix] + X[:, Parch_ix]
        
            return np.c_[X, value, total_family]
        else:
            return np.c_[X, value]
    
attr_adder = CombinedAttributesAdder(total_family = False)
titanic_extra_attribs = attr_adder.transform(titanic_new.values)

In [23]:
titanic_extra_attribs[130]

array([24.0, 0, 0, 13.0, 2, 'male', 0.0], dtype=object)

In [24]:
# Data Cleaning
# Set the missing values to some value (zero, the mean, the median, etc.)

# to find median 
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')

In [25]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
 ('imputer', SimpleImputer(missing_values=np.nan, strategy='median')),
 ('attribs_adder', CombinedAttributesAdder(total_family = False)),
 ('std_scaler', StandardScaler()),
 ])

titanic_num_tr = num_pipeline.fit_transform(titanic_new[num_features])

In [26]:
titanic_num_tr[0]

array([ 1.25364106, -0.47072241, -0.47934164, -0.07868358, -1.61413602,
       -0.52689001])

In [27]:
class DataFrameSelector(BaseEstimator, TransformerMixin):
    
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        return X[self.attribute_names].values

In [28]:
from sklearn.base import TransformerMixin 

class MyLabelBinarizer(TransformerMixin):

    def __init__(self, *args, **kwargs):
        self.encoder = LabelBinarizer(*args, **kwargs)

    def fit(self, x, y=0):
        self.encoder.fit(x)
        return self

    def transform(self, x, y=0):
        return self.encoder.transform(x)

In [29]:
# for training data

from sklearn.pipeline import FeatureUnion
from sklearn.preprocessing import LabelBinarizer
#num_attribs = list(housing_num)
#cat_attribs = ["ocean_proximity"]

num_pipeline = Pipeline([
 ('selector', DataFrameSelector(num_features)),
 ('imputer', SimpleImputer(missing_values=np.nan, strategy='median')),
 ('attribs_adder', CombinedAttributesAdder(total_family = False)),
 ('std_scaler', StandardScaler()),
 ])

cat_pipeline = Pipeline([
 ('selector', DataFrameSelector("Sex")),
 #('imputer', SimpleImputer(missing_values=np.nan, strategy='most_frequent')),
 ('label_binarizer', MyLabelBinarizer()),
 ])

full_pipeline = FeatureUnion(transformer_list=[
 ("num_pipeline", num_pipeline),
 ("cat_pipeline", cat_pipeline),
 ])

In [30]:
titanic_prepared = full_pipeline.fit_transform(titanic_new)

In [31]:
titanic_prepared

array([[ 1.25364106, -0.47072241, -0.47934164, ..., -1.61413602,
        -0.52689001,  1.        ],
       [-0.47728355, -0.47072241, -0.47934164, ..., -0.40055118,
        -0.52689001,  1.        ],
       [ 0.21508629, -0.47072241, -0.47934164, ...,  0.81303367,
        -0.52689001,  1.        ],
       ...,
       [ 0.90745614,  1.23056874, -0.47934164, ...,  0.81303367,
         0.7963752 ,  1.        ],
       [-1.1696534 ,  0.37992316,  2.04874166, ..., -1.61413602,
         1.45800781,  0.        ],
       [-0.63114352, -0.47072241,  0.78470001, ..., -1.61413602,
        -0.52689001,  1.        ]])

In [32]:
pd.DataFrame(titanic_prepared)

0         1         2         3         4         5    6
0    1.253641 -0.470722 -0.479342 -0.078684 -1.614136 -0.526890  1.0
1   -0.477284 -0.470722 -0.479342 -0.377145 -0.400551 -0.526890  1.0
2    0.215086 -0.470722 -0.479342 -0.474867  0.813034 -0.526890  1.0
3   -0.246494  0.379923 -0.479342 -0.476230  0.813034  0.134743  1.0
4   -1.785093  2.931860  2.048742 -0.025249  0.813034  2.119640  0.0
..        ...       ...       ...       ...       ...       ...  ...
707 -0.631144 -0.470722 -0.479342 -0.480162  0.813034 -0.526890  0.0
708 -0.092634 -0.470722 -0.479342 -0.030545 -1.614136 -0.526890  1.0
709  0.907456  1.230569 -0.479342 -0.355804  0.813034  0.796375  1.0
710 -1.169653  0.379923  2.048742  1.683201 -1.614136  1.458008  0.0
711 -0.631144 -0.470722  0.784700  0.860748 -1.614136 -0.526890  1.0

[712 rows x 7 columns]

In [33]:
titanic_labels = train_set[lable_feature].values.ravel()

In [34]:
titanic_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,

In [35]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
# features = ["Sex_female", "value", "Fare", "Embarked_C", "Parch", "Sex_male", "Age"]
train_data_only = titanic_prepared
lin_reg.fit(train_data_only, titanic_labels)

LinearRegression()

In [36]:
from sklearn.metrics import mean_squared_error

titanic_predictions = lin_reg.predict(train_data_only)
lin_mse = mean_squared_error(titanic_labels, titanic_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

0.3805643363437775

In [37]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=2)
model.fit(train_data_only, titanic_labels)
titanic_predictions = model.predict(train_data_only)

In [39]:
from sklearn.metrics import mean_squared_error

lin_mse = mean_squared_error(titanic_labels, titanic_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

0.36910155114301507

In [54]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor()
tree_reg.fit(titanic_prepared, titanic_labels)

DecisionTreeRegressor()

In [56]:
titanic_predictions = tree_reg.predict(titanic_prepared)
tree_mse = mean_squared_error(titanic_labels, titanic_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.11268970688334044

In [57]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(tree_reg, titanic_prepared, titanic_labels,
scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

In [58]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())

In [60]:
display_scores(rmse_scores)

Scores: [0.46428571 0.50717639 0.53733825 0.44676489 0.4250932  0.50406796
 0.48571133 0.48265697 0.47282986 0.51381539]
Mean: 0.4839739940394323
Standard deviation: 0.03169922821821056


In [61]:
lin_scores = cross_val_score(lin_reg, titanic_prepared, titanic_labels, scoring="neg_mean_squared_error", cv=10)

In [62]:
lin_rmse_scores = np.sqrt(-lin_scores)
display_scores(lin_rmse_scores)

Scores: [0.34753113 0.40833766 0.43895711 0.29951827 0.35976215 0.41327915
 0.4507728  0.38728525 0.41645707 0.31477716]
Mean: 0.3836677740367679
Standard deviation: 0.048824224305982475


In [64]:
rf_scores = cross_val_score(model, titanic_prepared, titanic_labels, scoring="neg_mean_squared_error", cv=10)

In [65]:
rf_rmse_scores = np.sqrt(-lin_scores)
display_scores(rf_rmse_scores)

Scores: [0.34753113 0.40833766 0.43895711 0.29951827 0.35976215 0.41327915
 0.4507728  0.38728525 0.41645707 0.31477716]
Mean: 0.3836677740367679
Standard deviation: 0.048824224305982475


In [103]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

param_grid = [
 {'n_estimators': [3, 10, 30, 40, 50, 60, 70], 'max_features': [2, 3, 4, 5, 6, 7]},
 {'bootstrap': [False], 'n_estimators': [3, 10, 30, 40, 50], 'max_features': [2, 3, 4, 5, 6]},
 ]

forest_reg = RandomForestRegressor()

grid_search = GridSearchCV(forest_reg, param_grid, cv=5, scoring='neg_mean_squared_error')

grid_search.fit(titanic_prepared, titanic_labels)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid=[{'max_features': [2, 3, 4, 5, 6, 7],
                          'n_estimators': [3, 10, 30, 40, 50, 60, 70]},
                         {'bootstrap': [False], 'max_features': [2, 3, 4, 5, 6],
                          'n_estimators': [3, 10, 30, 40, 50]}],
             scoring='neg_mean_squared_error')

In [104]:
grid_search.best_params_

{'max_features': 3, 'n_estimators': 70}

In [105]:
grid_search.best_estimator_

RandomForestRegressor(max_features=3, n_estimators=70)

In [106]:
cvres = grid_search.cv_results_

for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(np.sqrt(-mean_score), params)

0.43338610442939063 {'max_features': 2, 'n_estimators': 3}
0.3968904004472053 {'max_features': 2, 'n_estimators': 10}
0.38812703093092166 {'max_features': 2, 'n_estimators': 30}
0.38595318292569697 {'max_features': 2, 'n_estimators': 40}
0.3875167398559324 {'max_features': 2, 'n_estimators': 50}
0.3844982012098961 {'max_features': 2, 'n_estimators': 60}
0.38486661653993776 {'max_features': 2, 'n_estimators': 70}
0.42176801144383824 {'max_features': 3, 'n_estimators': 3}
0.3949070058047664 {'max_features': 3, 'n_estimators': 10}
0.38607671282160794 {'max_features': 3, 'n_estimators': 30}
0.386991838703808 {'max_features': 3, 'n_estimators': 40}
0.38369556882055433 {'max_features': 3, 'n_estimators': 50}
0.38566339327608373 {'max_features': 3, 'n_estimators': 60}
0.38343896345883594 {'max_features': 3, 'n_estimators': 70}
0.42316622054146374 {'max_features': 4, 'n_estimators': 3}
0.39234790545161574 {'max_features': 4, 'n_estimators': 10}
0.3860270512052673 {'max_features': 4, 'n_estimat

In [107]:
feature_importances = grid_search.best_estimator_.feature_importances_
feature_importances

array([0.25252585, 0.03721341, 0.03349544, 0.29425276, 0.08186512,
       0.02817463, 0.27247278])

In [49]:
X = full_pipeline.fit_transform(train_data[imp_features])
X[0]

array([-0.56573646,  0.43279337, -0.47367361, -0.50244517,  0.82737724,
        0.16129358,  1.        ])

In [50]:
test_feature_2 = ['Age', 'SibSp', 'Parch', 'Fare', 'Pclass', 'Sex']

X_test = full_pipeline.fit_transform(test_data[test_feature_2])
X_test[0]

array([ 0.38623105, -0.49947002, -0.4002477 , -0.49741333,  0.87348191,
       -0.54667747,  1.        ])

In [38]:
# Applying the random forest for regression

from sklearn.ensemble import RandomForestClassifier

#y = train_set["Survived"]

#features = ["Pclass", "Sex", "SibSp", "Parch"]

#X = pd.get_dummies(train_set[features])
#X_test = pd.get_dummies(test_set[features]) 
#y_test = test_set["Survived"]


# X = full_pipeline.fit_transform(train_data[imp_features])


y = train_data["Survived"]

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)


output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!
